---
- name: deploy and provision an attacker virtual machine
  hosts: localhost
  gather_facts: no
  environment:
    # VMWARE_HOST: "{{ vcenter_hostname }}"
    # VMWARE_USER: "{{ vcenter_username }}"
    # VMWARE_PASSWORD: "{{ vcenter_password }}"
    VMWARE_VALIDATE_CERTS: no
  vars:
    # folder: "{{ organization_folder }}/{{ pod_folder_name }}"
    # pod_folder_name: "oca-{{ pod_number}}: {{ pod_name }}"
    pod_folder_name: "oca-{{ '%03d' % pod_number }}"
    folder: "UBNetDef/vm/Arena/spearandshield/AttackMachines"
    # vm_name: "oca-{{ pod_number }}-{{ vm_number }}: {{ vm_template }}"
    vm_name: "oca-{{ '%03d' % pod_number }}-attacker"
    # vm_lan_address: "10.250.{{ pod_number }}.{{ vm_number }}"
    # vm_lan_gateway: "10.250.{{ pod_number }}.1"
  roles:
    - deploy_attacker
