---
- name: Remove folder
  hosts: localhost
  gather_facts: no
  environment:
    # VMWARE_HOST: "{{ vcenter_hostname }}"
    # VMWARE_USER: "{{ vcenter_username }}"
    # VMWARE_PASSWORD: "{{ vcenter_password }}"
    VMWARE_VALIDATE_CERTS: no
  vars:
    pod_folder: "{{ organization_folder }}/{{ pod_folder_name }}"
    # pod_folder_name: "oca-{{ pod_number}}: {{ pod_name }}"
    pod_folder_name: "oca-{{ '%03d' % pod_number }}"
  tasks:
    - set_fact:
        datacenter: "{{ vcenter_datacenter }}"

    # - name: Find Guest's Folder using name
    #   vmware_guest_find:
    #     name: oca-110-001
    #   delegate_to: localhost
    #   register: vm_folder
    - name: delete folder
      vcenter_folder:
        datacenter: "{{ vcenter_datacenter }}"
        folder_name: "{{ pod_folder_name }}"
        folder_type: vm
        state: absent