---
- name: Remove folder
  hosts: localhost
  gather_facts: no
  environment:
    # VMWARE_HOST: "{{ vcenter_hostname }}"
    # VMWARE_USER: "{{ vcenter_username }}"
    # VMWARE_PASSWORD: "{{ vcenter_password }}"
    VMWARE_VALIDATE_CERTS: no
  vars:
    pod_folder: "{{ organization_folder }}/{{ pod_folder_name }}"
    # pod_folder_name: "oca-{{ pod_number}}: {{ pod_name }}"
    pod_folder_name: "oca-{{ '%03d' % pod_number }}"
  tasks:
    - set_fact:
        datacenter: "{{ vcenter_datacenter }}"

    - name: delete folder
      community.vmware.vcenter_folder:
        # hostname: '{{ vcenter_hostname }}'
        # username: '{{ vcenter_username }}'
        # password: '{{ vcenter_password }}'
        datacenter_name: '{{ vcenter_datacenter }}'
        folder_name: '{{ pod_folder_name }}'
        parent_folder: '{{ organization_folder }}'
        state: absent
      # register: sub_folder_creation_result
      delegate_to: localhost