---
- name: deploy VM from template
  vmware_guest:
    datacenter: "{{ vcenter_datacenter }}"
    folder: "{{ pod_folder }}"
    cluster: "{{ vcenter_cluster }}"
    datastore: "{{ vcenter_datastore }}"
    name: "{{ vm_name }}"
    template: "{{ vm_template }}"
    networks:
      - name: "{{ vcenter_network }}"
        ip: "{{ vm_lan_address }}"
        gateway: "{{ vm_lan_gateway }}"
        netmask: "255.255.255.0"
        type: static
    customization:
      dns_servers:
        - 8.8.8.8
        - 8.8.4.4
    state: poweredon
    wait_for_ip_address: yes
- name: change VM password
  vmware_vm_shell:
    datacenter: "{{ vcenter_datacenter }}"
    folder: "{{ pod_folder }}"
    vm_id: "{{ vm_name }}"
    vm_username: "root"
    vm_password: "Changeme1!"
    # TODO: improve this.
    vm_shell: /opt/arena/change-password.sh
    vm_shell_env:
      - "USER_PASS=root:{{ vm_password }}\nsysadmin:{{ vm_password }}"
  when: vm_password is defined
