---
- name: deploy VyOS router from template
  vmware_guest:
    datacenter: "{{ vcenter_datacenter }}"
    folder: "{{ pod_folder }}"
    cluster: "{{ vcenter_cluster }}"
    datastore: "{{ vcenter_datastore }}"
    name: "{{ vm_name }}"
    template: "{{ vm_template }}"
    networks:
      - name: "{{ vcenter_network }}"
      - name: "{{ vcenter_network }}"
    state: poweredon
    wait_for_ip_address: yes
- name: configure VyOS router
  vmware_vm_shell:
    datacenter: "{{ vcenter_datacenter }}"
    folder: "{{ pod_folder }}"
    vm_id: "{{ vm_name }}"
    vm_username: "vyos"
    vm_password: "vyos"
    vm_shell: /opt/arena/configure-network.sh
    vm_shell_env:
      - "POD_LAN_CIDR={{ pod_lan_cidr }}"
      - "VM_LAN_CIDR={{ vm_lan_cidr }}"
      - "VM_WAN_CIDR={{ vm_wan_cidr }}"
- name: change VyOS password
  vmware_vm_shell:
    datacenter: "{{ vcenter_datacenter }}"
    folder: "{{ pod_folder }}"
    vm_id: "{{ vm_name }}"
    vm_username: "vyos"
    vm_password: "vyos"
    vm_shell: /opt/arena/change-password.sh
    vm_shell_env:
      - "PASSWORD={{ vm_password }}"
  when: vm_password is defined
