---
- name: deploy VyOS router from template
  vmware_guest:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: "{{ lookup('env', 'VMWARE_VALIDATE_CERTS') }}"
    datacenter: "{{ vcenter.datacenter }}"
    folder: "Arena/Pods/{{ pod.group }}/{{ pod.number }}: {{ pod.name }}"
    cluster: "{{ vcenter.cluster }}"
    datastore: "{{ vcenter.datastore }}"
    name: "arena-p{{ pod.number }}-v1"
    template: "VyOS"
    networks:
      - name: "{{ vcenter.network }}"
      - name: "{{ vcenter.network }}"
    state: poweredon
    wait_for_ip_address: yes
- name: configure VyOS router
  vmware_vm_shell:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: "{{ lookup('env', 'VMWARE_VALIDATE_CERTS') }}"
    datacenter: "{{ vcenter.datacenter }}"
    folder: "Arena/Pods/{{ pod.group }}/{{ pod.number }}: {{ pod.name }}"
    vm_id: "arena-p{{ pod.number }}-v1"
    vm_username: "vyos"
    vm_password: "vyos"
    vm_shell: /opt/arena/netconf.sh
    vm_shell_env:
      - "ARENA_POD_NUMBER={{ pod.number }}"
