---
- name: create folder
  vcenter_folder:
    datacenter: "{{ vcenter_datacenter }}"
    parent_folder: "{{ organization_folder }}"
    folder_name: "{{ pod_folder_name }}"
    folder_type: vm
    state: present
